allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msw: true

packages:
  - "packages/*"

catalog:
  react: ^19.3.0
  "@tanstack/react-query": "^5.103.1"
  "axios": "^1.20.0"
  "typescript": "^5.9.3"
  msw: ^2.15.0
  '@tailwindcss/vite': ^4.3.3
  tailwindcss: ^4.3.3

minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.11.25
