# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.3"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "..", "/vagrant"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "devops/ansible/playbooks/local.prep"
    ansible.install_mode = "pip"
    ansible.version = "2.2.1.0"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "devops/ansible/playbooks/dev.yml"
    ansible.install_mode = "pip"
    ansible.version = "2.2.1.0"
  end
end
