# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 22:36
from __future__ import unicode_literals

from django.db import migrations

def add_initial_workshop(apps, schema_editor):
    Workshop = apps.get_model("workshops", "Workshop")
    ws = Workshop(title="Austin Hackathon", access_code="C4*7^UYUC")
    ws.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_workshop)
    ]
