# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
options:
  max-time: 10 # configure default 10 minute timeout

pipelines:
  default:
    - parallel:
      - step:
          name: Server Side Unit Tests
          image: python:3.6
          caches:
            - pip
          script:
            - cd server
            - cp portal/templates/base.j2 portal/templates/base.html
            - mkdir -p log/portal
            - pip install -r requirements.txt
            - coverage run --branch --source="portal" --omit "*/*unit_test.py" manage.py test
              --pattern="*unit_test.py"
              -v2 --settings="portal.settings.unit_test_settings"
            - coverage xml -i
            - bash <(curl -s https://codecov.io/bash) -cF python
            - git fetch origin "+refs/heads/master:refs/remotes/origin/master"
            - cd ..
            - git diff -U0 origin/master..HEAD | flake8 --diff
      - step:
          name: Client Side Unit Tests
          image: node:lts
          caches:
            - client-node
          script:
            - cd client
            - npm install
            - npm run test
            - bash <(curl -s https://codecov.io/bash) -cF javascript
            - npm run lint

definitions:
  caches:
    client-node: client/node_modules
