---
- name: Provision local portal instance
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - group_vars/local.yml

  roles:
    - common
    - { role: selinux, when selinux_enabled == 'true' }
    - elasticsearch
