---
- name: Provision local portal instance
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - group_vars/local.yml

  roles:
    - { role: common,
        when: portal_upgrade == 'true' }
    - { role: selinux,
        when: selinux_enabled == 'true' }
    - { role: users,
        when: (inventory_hostname.startswith('ut-portal') or inventory_hostname.startswith('ut-workers') ) and
              portal_upgrade == 'true' }
    - { role: git,
        when: inventory_hostname.startswith('ut-portal') or inventory_hostname.startswith('ut-workers')}
    - { role: project_setup,
        when: inventory_hostname.startswith('ut-portal') or inventory_hostname.startswith('ut-workers')}
    - { role: nginx,
        when: inventory_hostname.startswith('ut-portal')}
    - { role: uwsgi,
        when: inventory_hostname.startswith('ut-portal')}
    - { role: rabbitmq,
        when: inventory_hostname.startswith('ut-workers') and
              'ansible' in group_names }
    - { role: redis,
        when: inventory_hostname.startswith('ut-workers')}
    - { role: celeryd,
        when: inventory_hostname.startswith('ut-workers')}
    - { role: elasticsearch,
        when: inventory_hostname.startswith('ut-elasticsearch')}
