- hosts: local
  become: yes
  become_user: root
  vars_files:
    - group_vars/local.yml
  roles:
    - common
    - users
    - elasticsearch
    - rabbitmq
    - redis
    - git
    - {role: postgres, tags: ['postgres']}
    - {role: newrelic, tags: ['deploy']}
    - {role: nginx, tags: ['deploy']}
    - {role: git, tags: ['deploy']}
    - {role: project_setup, tags: ['deploy']}
    - {role: celeryd, tags: ['deploy']}
    - {role: uwsgi, tags: ['deploy']}