---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: production
  roles:
    - {role: common, tags: ['provision']}
    - {role: users, tags: ['provision']}
    - {role: elasticsearch, tags: ['provision']}
    - {role: rabbitmq, tags: ['provision']}
    - {role: redis, tags: ['provision']}
    - {role: git, tags: ['provision']}
    - {role: newrelic, tags: ['provision']}
    - {role: nginx, tags: ['deploy']}
    - {role: git, tags: ['deploy']}
    - {role: project_setup, tags: ['deploy']}
    - {role: celeryd, tags: ['deploy']}
    - {role: uwsgi, tags: ['deploy']}
