services:
  django-common: 
    image: taccwma/core-portal:latest
    environment:
      TAS_CLIENT_SECRET: "${TAS_CLIENT_SECRET}"
      RT_PW: "${RT_PW}"
      AGAVE_CLIENT_KEY: "${AGAVE_CLIENT_KEY}"
      AGAVE_CLIENT_SECRET: "${AGAVE_CLIENT_SECRET}"
      AGAVE_SUPER_TOKEN: "${AGAVE_SUPER_TOKEN}"
      TAPIS_CLIENT_KEY: "${TAPIS_CLIENT_KEY}"
      TAPIS_ADMIN_JWT: "${TAPIS_ADMIN_JWT}"
      KEY_SERVICE_TOKEN: "${KEY_SERVICE_TOKEN}"
      ES_AUTH: "${ES_AUTH}"
      TAPIS_CLIENT_KEY_DEV: "${TAPIS_CLIENT_KEY_DEV}"
      TAPIS_ADMIN_JWT_DEV: "${TAPIS_ADMIN_JWT_DEV}"
      PORTAL_PROJECTS_PRIVATE_KEY: "${PORTAL_PROJECTS_PRIVATE_KEY}"
      PORTAL_PROJECTS_PUBLIC_KEY: "${PORTAL_PROJECTS_PUBLIC_KEY}"
      GOOGLE_DRIVE_CLIENT_SECRET: "${GOOGLE_DRIVE_CLIENT_SECRET}"
      GOOGLE_DRIVE_CLIENT_ID: "${GOOGLE_DRIVE_CLIENT_ID}"
      RECAPTCHA_SECRET_KEY: "${RECAPTCHA_SECRET_KEY}"
      RECAPTCHA_SITE_KEY: "${RECAPTCHA_SITE_KEY}"
      
