# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUrl',
            fields=[
                ('file_id', models.TextField(primary_key=True, serialize=False)),
                ('postit_url', models.TextField()),
                ('updated', models.DateTimeField()),
                ('expires', models.DateTimeField()),
            ],
        ),
    ]
