# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MATLABLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_file_content', models.TextField(help_text=b"This should be entire contents of the user's MATLAB license file. Please ensure you paste the license exactly as it is in the license file.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matlablicense', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
