---

- name: Install new relic repo
  command: "sudo curl -o /etc/yum.repos.d/newrelic-infra.repo https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/newrelic-infra.repo"

- name: Install newrelic-infra
  yum: name=newrelic-infra state=present

- name: Newrelic infra template
  template: src=newrelic-infra.yml.j2 dest=/etc/newrelic-infra.yml

- name: Newrelic APM template
  template: src=newrelic.ini.j2 dest=/etc/newrelic.ini

- name: Install newrelic admin
  pip:
    name: newrelic

- name: Add newrelic Yum repository
  yum_repository:
    name: newrelic-infra
    description: newrelic-infra
    baseurl: https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64/
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    gpgcheck: 1
    repo_gpgcheck: 1

- name: "install newrelic infra"
  yum:
    name: newrelic-infra

- name: Restart Newrelic infra
  service:
    name: newrelic-infra
    state: restarted
