# Generated by Django 2.2.7 on 2020-09-17 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.apps.webhooks.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCall',
            fields=[
                ('webhook_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('callback', models.CharField(max_length=300, null=True)),
                ('callback_data', portal.apps.webhooks.fields.JSONField(null=True)),
                ('accepting', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
