# Generated by Django 3.2.19 on 2023-05-04 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('webhooks', '0001_initial'), ('webhooks', '0002_auto_20221221_2114'), ('webhooks', '0003_alter_externalcall_callback_data')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCall',
            fields=[
                ('webhook_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('callback', models.CharField(max_length=300, null=True)),
                ('callback_data', models.JSONField(null=True)),
                ('accepting', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
