# Generated by Django 2.2.28 on 2022-12-21 21:14

from django.db import migrations
import portal.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcall',
            name='callback_data',
            field=portal.utils.fields.JSONField(null=True),
        ),
    ]
