# Generated by Django 3.2.19 on 2023-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20221221_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcall',
            name='callback_data',
            field=models.JSONField(null=True),
        ),
    ]
