# Generated by Django 4.2.10 on 2024-03-19 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_squashed_0003_alter_externalcall_callback_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcall',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
