# Generated by Django 2.2.7 on 2019-11-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField(unique=True)),
                ('private', models.TextField()),
                ('public', models.TextField()),
                ('ssh_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.SSHKeys')),
            ],
        ),
        migrations.CreateModel(
            name='HostKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('private', models.TextField()),
                ('public', models.TextField()),
                ('ssh_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.SSHKeys')),
            ],
            options={
                'unique_together': {('hostname', 'ssh_keys')},
            },
        ),
    ]
