# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-24 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_notificationpreferences_portalprofilenhinterests_portalprofileresearchactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField()),
                ('private', models.TextField()),
                ('public', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SSHKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('ojbects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='keys',
            name='ssh_keys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.SSHKeys'),
        ),
    ]
