# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180427_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='system',
            field=models.TextField(unique=True),
        ),
    ]
