# Generated by Django 3.2.20 on 2023-10-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210316_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='portalprofile',
            name='orcid_id',
        ),
        migrations.RemoveField(
            model_name='portalprofile',
            name='professional_level',
        ),
        migrations.RemoveField(
            model_name='portalprofile',
            name='website',
        ),
    ]
