# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180507_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='announcements',
            field=models.BooleanField(default=True, verbose_name='Receive occasional announcements from CEP'),
        ),
    ]
