# Generated by Django 5.2.13 on 2026-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231018_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalprofile',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portalprofile',
            name='orcid_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
