# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-28 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180607_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalprofile',
            name='setup_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='announcements',
            field=models.BooleanField(default=True, verbose_name='Receive occasional announcements from CEP.jchuah'),
        ),
    ]
