# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-04 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180607_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('private', models.TextField()),
                ('public', models.TextField()),
                ('ssh_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.SSHKeys')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hostkeys',
            unique_together=set([('hostname', 'ssh_keys')]),
        ),
    ]
