# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190128_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalprofile',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
