# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-14 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190314_1848'),
        ('accounts', '0007_auto_20190204_2346'),
    ]

    operations = [
    ]
