# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20190314_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='announcements',
            field=models.BooleanField(default=True, verbose_name='Receive occasional announcements from CEP'),
        ),
    ]
