# Generated by Django 2.2.28 on 2022-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_messages', '0006_auto_20220926_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Message content (max 1000 characters)', max_length=1000),
        ),
    ]
