# Generated by Django 5.2.13 on 2026-07-03 17:49

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('publications', '0001_initial'), ('publications', '0002_alter_publicationrequest_review_project_and_more'), ('publications', '0003_publication')]

    dependencies = [
        ('projects', '0005_projectsmetadata_created_at_and_more'),
        ('projects', '0007_projectmetadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('review_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_reviews', to='projects.projectmetadata')),
                ('reviewers', models.ManyToManyField(related_name='publication_reviewers', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_publication_reviews', to='projects.projectmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('project_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('value', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Value for the project's base metadata, including title/description/users")),
                ('tree', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON document containing the serialized publication tree')),
            ],
        ),
    ]
