# Generated by Django 5.2.17 on 2026-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial_squashed_0003_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="is_indexable",
            field=models.BooleanField(
                default=True,
                help_text="Whether the landing page may be indexed and listed in the sitemap. publish_project clears it; it's set again once the files have been transferred and the DOI is findable.",
            ),
        ),
    ]
