# Generated by Django 5.2.17 on 2026-10-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_publication_is_indexable"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="archive_sha256",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sha256 of the current version's whole-publication ZIP, read from the archive job's <workspace id>_archive.zip.sha256. Empty until it's loaded, and cleared on every publish.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="archive_size",
            field=models.BigIntegerField(
                blank=True, help_text="Size in bytes of that ZIP, recorded with its sha256.", null=True
            ),
        ),
    ]
