# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-18 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.apps.googledrive_integration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', portal.apps.googledrive_integration.models.CredentialsField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googledrive_user_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
