# Generated by Django 4.2.7 on 2024-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0002_auto_20230317_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilesMetadata',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
