# Generated by Django 4.2.7 on 2024-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectsmetadata'),
        ('datafiles', '0002_auto_20230317_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilesMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datafiles.datafilesmetadata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='projects.projectsmetadata')),
            ],
        ),
    ]
