# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# portal.apps.projects.migrations.0002_auto_20180914_1814

def add_initial_project_id(apps, schema_editor):
    """Create first record for project Id."""
    ProjectId = apps.get_model('projects', 'ProjectId')
    ProjectId.objects.create(value=1)

class Migration(migrations.Migration):

    replaces = [(b'projects', '0001_initial'), (b'projects', '0002_auto_20180914_1814'), (b'projects', '0003_abstractprojectmetadata_projectmetadata'), (b'projects', '0004_auto_20181108_1950'), (b'projects', '0005_auto_20181109_0148')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_initial_project_id),
        migrations.CreateModel(
            name='AbstractProjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('project_id', models.CharField(max_length=255)),
                ('pi', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('abstractprojectmetadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.AbstractProjectMetadata')),
            ],
            bases=('projects.abstractprojectmetadata',),
        ),
        migrations.AddField(
            model_name='abstractprojectmetadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractprojectmetadata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='project_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='abstractprojectmetadata',
            name='co_pis',
            field=models.ManyToManyField(related_name='rel_co_pi_abstractprojectmetadata', related_query_name='co_pi_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractprojectmetadata',
            name='team_members',
            field=models.ManyToManyField(related_name='rel_member_abstractprojectmetadata', related_query_name='member_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_pi_abstractprojectmetadata', related_query_name='pi_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
