# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-09 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_squashed_0005_auto_20181109_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='co_pis',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_co_pi_abstractprojectmetadata', related_query_name='co_pi_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_pi_abstractprojectmetadata', related_query_name='pi_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_member_abstractprojectmetadata', related_query_name='member_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
