# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181109_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprojectmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
