# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20181112_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprojectmetadata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_owner_abstractprojectmetadata', related_query_name='owner_abstractprojectmetadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
