# Generated by Django 5.2.13 on 2026-07-03 18:11

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import portal.apps.projects.models.project_metadata
from django.conf import settings
from django.db import migrations, models
from portal.apps.projects.schema_models import constants

class Migration(migrations.Migration):

    replaces = [('projects', '0004_projectsmetadata'), ('projects', '0005_projectsmetadata_created_at_and_more'), ('projects', '0006_rename_projectmetadata_legacyprojectmetadata'), ('projects', '0007_projectmetadata_and_more'), ('projects', '0008_delete_projectsmetadata')]

    dependencies = [
        ('projects', '0003_alter_abstractprojectmetadata_co_pis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMetadata',
            new_name='LegacyProjectMetadata',
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('uuid', models.CharField(default=portal.apps.projects.models.project_metadata.uuid_pk, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Metadata namespace, e.g. 'designsafe.project'", max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('value', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='JSON document containing file metadata, including title/description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('base_project', models.ForeignKey(help_text='Base project containing this entity.For top-level project metadata, this is `self`.', on_delete=django.db.models.deletion.CASCADE, to='projects.projectmetadata')),
                ('users', models.ManyToManyField(help_text='Users who have access to a project.', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(models.F('value__projectId'), name='value_project_id'), models.Index(fields=['name'], name='projects_pr_name_5382e9_idx')],
                'constraints': [models.UniqueConstraint(models.F('value__projectId'), condition=models.Q(('name', constants.PROJECT)), name='unique_id_per_project'), models.UniqueConstraint(condition=models.Q(('name', constants.PROJECT_GRAPH)), fields=('base_project_id',), name='unique_graph_per_project'), models.CheckConstraint(condition=models.Q(('name', constants.PROJECT), ('value__projectId__isnull', True), _negated=True), name='base_projectId_not_null')],
            },
        ),
    ]
