# Generated by Django 4.2.11 on 2024-06-05 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectsmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmetadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsmetadata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
