# Generated by Django 4.2.11 on 2024-09-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectsmetadata_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMetadata',
            new_name='LegacyProjectMetadata',
        ),
    ]
