# Generated by Django 2.2.28 on 2022-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas_project_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasprojectsystementry',
            name='projectid',
            field=models.CharField(default='test', help_text='A projectid value to use for generating systems. Must be all lowercase, one word, no punctuation', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasprojectsystementry',
            name='projectname',
            field=models.CharField(help_text='The project name for display and description purposes', max_length=64),
        ),
    ]
