# Generated by Django 3.2.19 on 2023-05-04 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('workspace', '0001_initial'), ('workspace', '0002_auto_20200218_2115'), ('workspace', '0003_apptraycategory_apptrayentry'), ('workspace', '0004_jobsubmission_data'), ('workspace', '0004_auto_20221013_2240'), ('workspace', '0005_merge_20230119_1627'), ('workspace', '0006_alter_jobsubmission_data')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTrayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='A category for the app tray', max_length=64)),
                ('priority', models.IntegerField(default=0, help_text='Category priority, where higher priority tabs appear before lower ones')),
            ],
        ),
        migrations.CreateModel(
            name='AppTrayEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='The display name of this app in the App Tray', max_length=64)),
                ('icon', models.CharField(blank=True, help_text='The icon to apply to this application', max_length=64)),
                ('version', models.CharField(blank=True, help_text='The version number of the app', max_length=64)),
                ('appId', models.CharField(help_text='The id of this app. The app id + version denotes a unique app', max_length=64)),
                ('appType', models.CharField(choices=[('tapis', 'Tapis'), ('html', 'HTML')], default='tapis', help_text='Application type', max_length=10)),
                ('html', models.TextField(blank=True, default='', help_text='HTML definition to display when Application is loaded')),
                ('available', models.BooleanField(default=True, help_text='App visibility in app tray')),
                ('category', models.ForeignKey(help_text='The App Category for this app entry', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspace.apptraycategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobId', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
