# Generated by Django 2.2.7 on 2020-02-18 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
