# Generated by Django 2.2.16 on 2020-11-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20200218_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTrayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='A category for the app tray', max_length=64)),
                ('priority', models.IntegerField(default=0, help_text='Category priority, where higher priority tabs appear before lower ones')),
            ],
        ),
        migrations.CreateModel(
            name='AppTrayEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The short name of the Agave app', max_length=64)),
                ('label', models.CharField(help_text='The display name of this app in the App Tray', max_length=64)),
                ('icon', models.CharField(blank=True, help_text='The icon to apply to this application', max_length=64)),
                ('version', models.CharField(blank=True, help_text='The version number of the app', max_length=64)),
                ('revision', models.CharField(blank=True, help_text='The revision of the app', max_length=3)),
                ('appId', models.CharField(blank=True, help_text='Specifying an app by id will override all other app specifications', max_length=64)),
                ('lastRetrieved', models.CharField(help_text='The latest retrieved version of this app', max_length=64)),
                ('appType', models.CharField(choices=[('agave', 'agave'), ('html', 'html')], default='agave', help_text='Application type', max_length=10)),
                ('html', models.TextField(blank=True, default='', help_text='HTML definition to display when Application is loaded')),
                ('htmlId', models.CharField(blank=True, help_text='A non-agave portal specific ID for an HTML app', max_length=64)),
                ('available', models.BooleanField(default=True, help_text='App visibility in app tray')),
                ('shortDescription', models.TextField(blank=True, default='', help_text='App short description')),
                ('category', models.ForeignKey(help_text='The App Category for this app entry', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspace.AppTrayCategory')),
            ],
        ),
    ]
