# Generated by Django 2.2.28 on 2022-12-12 20:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_apptraycategory_apptrayentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
