# Generated by Django 2.2.28 on 2022-12-21 21:14

from django.db import migrations
import portal.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_apptraycategory_apptrayentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='data',
            field=portal.utils.fields.JSONField(null=True),
        ),
    ]
