# Generated by Django 2.2.28 on 2022-10-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_apptraycategory_apptrayentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptrayentry',
            name='htmlId',
        ),
        migrations.RemoveField(
            model_name='apptrayentry',
            name='lastRetrieved',
        ),
        migrations.RemoveField(
            model_name='apptrayentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apptrayentry',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='apptrayentry',
            name='shortDescription',
        ),
        migrations.AddField(
            model_name='apptrayentry',
            name='description',
            field=models.TextField(blank=True, default='', help_text='App description'),
        ),
        migrations.AlterField(
            model_name='apptrayentry',
            name='appId',
            field=models.CharField(help_text='The id of this app. The app id + version denotes a unique app', max_length=64),
        ),
        migrations.AlterField(
            model_name='apptrayentry',
            name='appType',
            field=models.CharField(choices=[('tapis', 'Tapis'), ('html', 'HTML')], default='tapis', help_text='Application type', max_length=10),
        ),
        migrations.AlterField(
            model_name='apptrayentry',
            name='label',
            field=models.CharField(blank=True, help_text='The display name of this app in the App Tray', max_length=64),
        ),
    ]
