# Generated by Django 2.2.28 on 2023-01-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_jobsubmission_data'),
        ('workspace', '0004_auto_20221013_2240'),
    ]

    operations = [
    ]
