# Generated by Django 2.2.28 on 2022-12-15 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20221013_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsubmission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
