# Generated by Django 3.2.19 on 2023-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_merge_20230119_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmission',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
