# Generated by Django 2.2.27 on 2022-03-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intromessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Dashboard', 'dashboard'), ('Data Files', 'datafiles'), ('Applications', 'applications'), ('Allocations', 'allocations'), ('History', 'history'), ('Account', 'account')], default='Dashboard', help_text='Component type', max_length=20)),
                ('message_type', models.CharField(choices=[], default='info', help_text='Message type', max_length=20)),
                ('dismissible', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='', help_text='Message content')),
            ],
        ),

        migrations.CreateModel(
            name='CustomMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='intromessages.CustomMessageTemplate')),
                ('unread', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
    ]

