- name: Copy repo service account ssh key
  copy: src='../../secret_files/bitbucket' dest=/root/.ssh/bitbucket

- name: Set ssh key perms
  file:
    path: /root/.ssh/bitbucket
    mode: 0600

- name: Copy SSH config file
  copy: src="ssh_config" dest="/root/.ssh/config"

- name: Get git repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_home_dir }}/{{ project_name }}"
    version: "{{ git_repo_version }}"
    recursive: "{{git_recursive}}"
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no -o ForwardAgent=yes"
