- name: Manually create .ssh directory
  file:
    path: "/root/.ssh"
    state: "directory"
    owner: root
    group: root

- name: Copy repo service account ssh key
  copy: src='../../secret_files/bitbucket' dest=/root/.ssh/bitbucket
  when: git_copy_ssh_key

- name: Set ssh key perms
  file:
    path: /root/.ssh/bitbucket
    mode: 0600
  when: git_copy_ssh_key

- name: Copy SSH config file
  copy: src="ssh_config" dest="/root/.ssh/config"
  when: git_copy_ssh_key

- name: Get git repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_home_dir }}/{{ project_name }}"
    version: "{{ git_repo_version }}"
    recursive: "{{git_recursive}}"
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no -o ForwardAgent=yes"

- name: transfer portal ownership to portal
  file:
    path: "/srv/www/portal"
    state: "directory"
    owner: portal
    group: portal
    recurse: yes
